# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
#     branches: [ master ]
  pull_request:
#     branches: [ master ]

jobs:
  buildAndroidAndWeb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Flutter action
      uses: subosito/flutter-action@v1.3.2
      with:
        channel: 'beta'
    - run: flutter config --enable-web
    - run: flutter build web

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: build/web
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - run: flutter build apk
  
    - name: Upload Diawi
      uses: rnkdsh/action-upload-diawi@v1.1.0
      with: 
        token: ${{ secrets.DIAWI_TOKEN }} 
        file: build/app/outputs/flutter-apk/app-release.apk
        #password: 'razern'
    - uses: actions/upload-artifact@v1
      with:
        name: apk
        path: build/app/outputs/flutter-apk/app-release.apk

  buildIos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1

    - name: Flutter action
      uses: subosito/flutter-action@v1.3.2
      with:
        channel: 'dev'

    - run: flutter build ios --profile --no-codesign #--debug

    - name: make folder, add .app then zip it and rename it to .ipa 
      run: |
        mkdir -p Payload 
        mv ./build/ios/iphoneos/Runner.app Payload 
        zip -r -y Payload.zip Payload/Runner.app 
        mv Payload.zip Payload.ipa

    - uses: actions/upload-artifact@v1
      id: diawi
      with:
        name: ipa
        path: Payload.ipa

    - name: Upload Diawi
      uses: rnkdsh/action-upload-diawi@v1.1.0
      with: 
        token: ${{ secrets.DIAWI_TOKEN }} 
        file: Payload.ipa

    - run: echo "check here:\n ${{ steps.diawi.outputs['url'] }}"
